apiVersion: v1
kind: Namespace
metadata:
  name: ha-controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: piraeus-ha-controller
  namespace: ha-controller
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: piraeus-ha-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: piraeus-ha-controller
    spec:
      serviceAccountName: ha-controller
      containers:
        - name: controller
          image: quay.io/piraeusdatastore/piraeus-ha-controller:v0.1.2
          args:
            - --leader-election=true
            - --leader-election-lease-name=$(NAME)
            - --leader-election-namespace=$(NAMESPACE)
            - --v=5
          env:
            - name: LS_CONTROLLERS
              value: http://piraeus-op-cs.default.svc:3370
            - name: NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          livenessProbe:
            httpGet:
              port: 8080
              path: /healthz
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: piraeus-ha-controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ha-controller
  namespace: ha-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ha-controller
rules:
  - verbs:
      - list
      - watch
      - delete
    apiGroups:
      - ""
    resources:
      - pods
  - apiGroups:
      - storage.k8s.io
    resources:
      - volumeattachments
    verbs:
      - list
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ha-controller
  namespace: ha-controller
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ha-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ha-controller
subjects:
  - kind: ServiceAccount
    name: ha-controller
    namespace: ha-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ha-controller
  namespace: ha-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ha-controller
subjects:
  - kind: ServiceAccount
    name: ha-controller
    namespace: ha-controller
